name: "API Client Base"
description: "Recipe for repeatable test setup for Drupal API client."
type: "Site"

install:
  - basic_auth
  - simple_oauth
config:
  actions:
    system.performance:
      simple_config_update:
        cache.page.max_age: 3600
