name: "API Client JSON:API"
description: "Recipe for repeatable test setup for Drupal JSON:API client."
type: "Site"

install:
  - jsonapi
  - decoupled_router
  - jsonapi_extras
  - jsonapi_views
config:
  actions:
    jsonapi.settings:
      simple_config_update:
        read_only: 0
