name: "API Client GraphQL"
description: "Recipe for repeatable test setup for Drupal GraphQL client."
type: "Site"

install:
  - graphql_compose
  - graphql_compose_edges
# config:
#   actions:
#     # Set permissions for anonymous role.
#     user.role.anonymous:
#       ensure_exists:
#         id: anonymous
#       grantPermissions:
#         - "view sanctuary_settings config page entity"
#     system.theme:
#       simple_config_update:
#         default: "claro"
